name: Pull Request Build

on:
  pull_request:
    types: [ labeled, synchronize ]

jobs:
  build:
      if: ${{ (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'run-build')) || (github.event.action == 'labeled' && github.event.label.name == 'run-build') }}
      runs-on: ubuntu-latest
      steps:
          - run: echo Build

