name: Reviewpad v3 With Token

on: pull_request

jobs:
  reviewpad_v3_with_token:
    runs-on: ubuntu-latest
    steps:
      - name: Reviewpad
        uses: reviewpad/action@v3.x
        with:
          token: ${{ secrets.REVIEWPAD_TOKEN }}