# This file configures Reviewpad action to run on Issues and Pull Requests! 🦄
name: Reviewpad

on:
  issue_comment:
    types: [created]

jobs:
  reviewpad_job:
    name: Reviewpad
    if: ${{ startsWith(github.event.comment.body, '/reviewpad merge') }}
    runs-on: ubuntu-latest
    steps:
      - name: Reviewpad
        uses: reviewpad/action@v3.x
        with:
          # Use a default configuration file.
          # Remove next line if you want to add your own configuration.
          # file_url: https://github.com/reviewpad/action/blob/main/templates/start.yml

          # Uncomment next line to use your own configuration file 💪
          file: reviewpad.yml
          token: ${{ secrets.REVIEWPAD_TOKEN}}
