name: Reviewpad

on:
  pull_request_target:
  pull_request_review:

jobs:
  reviewpad_canary_with_token:
    runs-on: ubuntu-latest
    steps:
      - name: Reviewpad
        uses: reviewpad/action@canary
        with:
          token: ${{ secrets.REVIEWPAD_TOKEN }}