name: reviewpad_dev

on:
  pull_request_target:
    types:
      - synchronize

jobs:
  reviewpad_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Reviewpad
        uses: reviewpad/action@dev/rebase
        with:
          token: ${{ secrets.REVIEWPAD_TOKEN }}