name: Reviewpad Action

# List of events that will trigger reviewpad
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft
      - edited
      - review_requested
      - review_request_removed
  pull_request_review:
  pull_request_review_comment:

jobs:
  reviewpad_without_token:
    runs-on: ubuntu-latest
    steps:
      - name: Reviewpad
        uses: reviewpad/action@v3.x
