name: Reviewpad

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft
      - edited
      - review_requested
      - review_request_removed

jobs:
  reviewpad:
    runs-on: ubuntu-latest
    steps:
      - name: Reviewpad
        uses: reviewpad/action@dev/rebase
        with:
          token: ${{ secrets.REVIEWPAD_TOKEN }}