name: Reviewpad Action Token

on: pull_request_target

jobs:
  reviewpad_token:
    runs-on: ubuntu-latest
    steps:
      - name: Reviewpad
        uses: reviewpad/action@v3.x
        with:
          token: ${{ secrets.REVIEWPAD_TOKEN }}
          
